# --- RED ---
spark.driver.bindAddress                0.0.0.0
spark.executor.hostname                 0.0.0.0
spark.network.timeout                   120s
spark.rpc.lookupTimeout                 120s

# --- RECURSOS (Single Node 32GB) ---
# Executor: 4GB. Permite ~4 o 5 ejecutores simultáneos en los 20GB disponibles.
spark.executor.memory                   4g
spark.driver.memory                     2g
spark.executor.cores                    1

# --- DYNAMIC ALLOCATION ---
spark.dynamicAllocation.enabled         true
spark.dynamicAllocation.minExecutors    0
spark.dynamicAllocation.maxExecutors    5

spark.dynamicAllocation.executorIdleTimeout        60s
spark.dynamicAllocation.cachedExecutorIdleTimeout  300s

# --- OPTIMIZACIÓN ---
spark.sql.adaptive.enabled              true
spark.serializer                        org.apache.spark.serializer.KryoSerializer
spark.ui.showConsoleProgress            true

# --- PARALELISMO ---
# 6 Cores * 3 = 18 particiones.
spark.default.parallelism               18
spark.sql.shuffle.partitions            18