version: '3.9'

networks:
  hadoop-net:
    driver: bridge

configs:
  ### Imagen: alumno-spark ###
  core-site-alumno-spark.xml:
    file: ./AlumnoSpark/Config-files/core-site.xml
  spark-defaults-alumno-spark.conf:
    file: ./AlumnoSpark/Config-files/spark-defaults.conf
  yarn-site-alumno-spark.xml:
    file: ./AlumnoSpark/Config-files/yarn-site.xml

  ### Imagen: dnnm-image ###
  core-site-dnnm.xml:
    file: ./DataNode-NodeManager/Config-files/core-site.xml
  hadoop-env-dnnm.sh:
    file: ./DataNode-NodeManager/Config-files/hadoop-env.sh
  hdfs-site-dnnm.xml:
    file: ./DataNode-NodeManager/Config-files/hdfs-site.xml
  mapred-site-dnnm.xml:
    file: ./DataNode-NodeManager/Config-files/mapred-site.xml
  spark-defaults-dnnm.conf:
    file: ./DataNode-NodeManager/Config-files/spark-defaults.conf
  yarn-site-dnnm.xml:
    file: ./DataNode-NodeManager/Config-files/yarn-site.xml

  ### Imagen: namenode-image ###
  core-site-namenode.xml:
    file: ./NameNode/Config-files/core-site.xml
  hadoop-env-namenode.sh:
    file: ./NameNode/Config-files/hadoop-env.sh
  hdfs-site-namenode.xml:
    file: ./NameNode/Config-files/hdfs-site.xml
  
  ### Imagen: resourcemanager-image ###
  core-site-resourcemanager.xml:
    file: ./ResourceManager/Config-files/core-site.xml
  hadoop-env-resourcemanager.sh:
    file: ./ResourceManager/Config-files/hadoop-env.sh
  mapred-site-resourcemanager.xml:
    file: ./ResourceManager/Config-files/mapred-site.xml
  spark-defaults-resourcemanager.conf:
    file: ./ResourceManager/Config-files/spark-defaults.conf
  yarn-site-resourcemanager.xml:
    file: ./ResourceManager/Config-files/yarn-site.xml

services:

  # -------------------#
  # NameNode (Manager) #
  # -------------------#
  namenode:
    image: namenode-image:latest
    container_name: namenode
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
      - target: 9870
        published: 9870
        protocol: tcp
        mode: host
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    networks:
      - hadoop-net
    configs:
      - source: core-site-namenode.xml
        target: /opt/bd/hadoop/etc/hadoop/core-site.xml
      - source: hadoop-env-namenode.sh
        target: /opt/bd/hadoop/etc/hadoop/hadoop-env.sh
      - source: hdfs-site-namenode.xml
        target: /opt/bd/hadoop/etc/hadoop/hdfs-site.xml
    deploy:
      resources:
        limits:
          memory: 4G

  # --------------------------#
  # ResourceManager (Manager) #
  # --------------------------#
  resourcemanager:
    image: resourcemanager-image:latest
    container_name: resourcemanager
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
        mode: host
    networks:
      - hadoop-net
    configs:
      - source: core-site-resourcemanager.xml
        target: /opt/bd/hadoop/etc/hadoop/core-site.xml
      - source: hadoop-env-resourcemanager.sh
        target: /opt/bd/hadoop/etc/hadoop/hadoop-env.sh
      - source: mapred-site-resourcemanager.xml
        target: /opt/bd/hadoop/etc/hadoop/mapred-site.xml
      - source: spark-defaults-resourcemanager.conf
        target: /opt/bd/spark/spark-3.5.2-bin-hadoop3/conf/spark-defaults.conf
      - source: yarn-site-resourcemanager.xml
        target: /opt/bd/hadoop/etc/hadoop/yarn-site.xml
    deploy:
      resources:
        limits:
          memory: 5G

  # ---------------------------------#
  # DataNode + NodeManager (Worker)  #
  # ---------------------------------#
  dnnm:
    image: dnnm-image:latest
    container_name: dnnm
    hostname: dnnm
    command: /opt/bd/start-daemons.sh
    networks:
      - hadoop-net
    configs:
      - source: core-site-dnnm.xml
        target: /opt/bd/hadoop/etc/hadoop/core-site.xml
      - source: hadoop-env-dnnm.sh
        target: /opt/bd/hadoop/etc/hadoop/hadoop-env.sh
      - source: hdfs-site-dnnm.xml
        target: /opt/bd/hadoop/etc/hadoop/hdfs-site.xml
      - source: mapred-site-dnnm.xml
        target: /opt/bd/hadoop/etc/hadoop/mapred-site.xml
      - source: spark-defaults-dnnm.conf
        target: /opt/bd/spark/spark-3.5.2-bin-hadoop3/conf/spark-defaults.conf
      - source: yarn-site-dnnm.xml
        target: /opt/bd/hadoop/etc/hadoop/yarn-site.xml
    deploy:
      resources:
        limits:
          memory: 22G

  #------------#
  # JupyterHub #
  #------------#
  jupyterhub:
    image: jupyterhub:latest
    container_name: jupyterhub
    networks:
      - hadoop-net
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - ./NameNode/Config-files/core-site.xml:/srv/jupyterhub/core-site.xml
      - ./ResourceManager/Config-files/yarn-site-resourcemanager.xml:/srv/jupyterhub/yarn-site.xml
      - ./NameNode/Config-files/hdfs-site-namenode.xml:/srv/jupyterhub/hdfs-site.xml
    environment:
      DOCKER_NETWORK_NAME: hadoop-net
      HUB_IP: jupyterhub
      DOCKER_JUPYTER_IMAGE: alumno-spark:latest
      JUPYTERHUB_CRYPT_KEY: "c3b5a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0"
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  jupyterhub_data: