version: '3.9'

networks:
  hadoop-net:
    driver: bridge

services:

  # -------------------#
  # NameNode (Manager) #
  # -------------------#
  namenode:
    image: namenode-image:latest
    container_name: namenode
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop-net
    volumes:
      - ./NameNode/Config-files/core-site.xml:/opt/bd/hadoop/etc/hadoop/core-site.xml
      - ./NameNode/Config-files/hdfs-site-namenode.xml:/opt/bd/hadoop/etc/hadoop/hdfs-site.xml
      - ./NameNode/Config-files/hadoop-env.sh:/opt/bd/hadoop/etc/hadoop/hadoop-env.sh
    environment:
      - HADOOP_FORMAT_ON_START=true

  # --------------------------#
  # ResourceManager (Manager) #
  # --------------------------#
  resourcemanager:
    image: resourcemanager-image:latest
    container_name: resourcemanager
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
      - "8088:8088"
    networks:
      - hadoop-net
    volumes:
      - ./ResourceManager/Config-files/core-site.xml:/opt/bd/hadoop/etc/hadoop/core-site.xml
      - ./ResourceManager/Config-files/yarn-site-resourcemanager.xml:/opt/bd/hadoop/etc/hadoop/yarn-site.xml
      - ./ResourceManager/Config-files/hadoop-env.sh:/opt/bd/hadoop/etc/hadoop/hadoop-env.sh

  # ---------------------------------#
  # DataNode + NodeManager (Worker)  #
  # ---------------------------------#
  dnnm:
    image: dnnm-image:latest
    container_name: dnnm
    hostname: dnnm
    command: /opt/bd/start-daemons.sh
    networks:
      - hadoop-net
    volumes:
      - ./DataNode-NodeManager/Config-files/core-site.xml:/opt/bd/hadoop/etc/hadoop/core-site.xml
      - ./DataNode-NodeManager/Config-files/yarn-site-nodemanager.xml:/opt/bd/hadoop/etc/hadoop/yarn-site.xml
      - ./DataNode-NodeManager/Config-files/hdfs-site-datanode.xml:/opt/bd/hadoop/etc/hadoop/hdfs-site.xml
      - ./DataNode-NodeManager/Config-files/hadoop-env.sh:/opt/bd/hadoop/etc/hadoop/hadoop-env.sh
      - ./DataNode-NodeManager/Config-files/mapred-site.xml:/opt/bd/hadoop/etc/hadoop/mapred-site.xml
      - ./DataNode-NodeManager/Config-files/spark-defaults.conf:/opt/bd/spark/spark-3.5.0-bin-hadoop3/conf/spark-defaults.conf
    deploy:
      resources:
        limits:
          memory: 22G

  #------------#
  # JupyterHub #
  #------------#
  jupyterhub:
    image: jupyterhub:latest
    container_name: jupyterhub
    networks:
      - hadoop-net
    ports: 
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - ./NameNode/Config-files/core-site.xml:/srv/jupyterhub/core-site.xml
      - ./ResourceManager/Config-files/yarn-site-resourcemanager.xml:/srv/jupyterhub/yarn-site.xml
      - ./NameNode/Config-files/hdfs-site-namenode.xml:/srv/jupyterhub/hdfs-site.xml
    environment:
      DOCKER_NETWORK_NAME: hadoop-net
      HUB_IP: jupyterhub
      DOCKER_JUPYTER_IMAGE: alumno-spark:latest
      JUPYTERHUB_CRYPT_KEY: "c3b5a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0"
    deploy:
      replicas: 1

volumes:
  jupyterhub_data: