# --- RED ---
spark.driver.bindAddress                0.0.0.0
spark.executor.hostname                 0.0.0.0
spark.network.timeout                   120s
spark.rpc.lookupTimeout                 120s

# --- RECURSOS ---
# Optimizamos para contenedores de 1.5GB RAM + Overhead = ~1.9GB
# Esto permite meter aprox 3 ejecutores por cada nodo Worker (6GB capacidad)
spark.executor.memory                   1536m
spark.driver.memory                     1g
spark.executor.cores                    1

# --- DYNAMIC ALLOCATION ---
spark.dynamicAllocation.enabled         true
spark.dynamicAllocation.minExecutors    0
# LIMITAMOS a 5 ejecutores por usuario. 
# Si 10 usuarios corren a la vez, se encolarán un poco, pero todos podrán trabajar.
spark.dynamicAllocation.maxExecutors    5

spark.dynamicAllocation.executorIdleTimeout        60s
spark.dynamicAllocation.cachedExecutorIdleTimeout  300s

# --- SHUFFLE SERVICE ---
# Recomendado habilitar si usas Dynamic Allocation
spark.shuffle.service.enabled           true

# --- OPTIMIZACIÓN ---
spark.sql.adaptive.enabled              true
spark.sql.adaptive.coalescePartitions.enabled true
spark.serializer                        org.apache.spark.serializer.KryoSerializer

# --- LOGS ---
spark.ui.showConsoleProgress            true