# --- RED ---
spark.driver.bindAddress                0.0.0.0
spark.executor.hostname                 0.0.0.0
spark.network.timeout                   120s
spark.rpc.lookupTimeout                 120s

# --- MODO DE DESPLIEGUE POR DEFECTO ---
# Fuerza a que Spark siempre busque al ResourceManager de YARN
spark.master                            yarn

# Mantiene el Driver en Jupyter, pero manda todo el procesamiento pesado a los 12 workers
spark.submit.deployMode                 client

# --- RECURSOS ---
# Asignamos 5GB de RAM por ejecutor. Como YARN toemne 7GB por nodo,
# entrará un Ejecutor grande y potente por cada réplica de NodeManager
spark.executor.memory                   5g
spark.driver.memory                     4g
# Usamos 4 hilos por ejecutor para paralelismo
spark.executor.cores                    4

# --- DYNAMIC ALLOCATION ---
spark.dynamicAllocation.enabled         true
spark.dynamicAllocation.minExecutors    1
spark.dynamicAllocation.maxExecutors    24

spark.dynamicAllocation.executorIdleTimeout        60s
spark.dynamicAllocation.cachedExecutorIdleTimeout  300s

# --- SHUFFLE SERVICE ---
# Recomendado habilitar si usas Dynamic Allocation
spark.shuffle.service.enabled           true

# --- OPTIMIZACIÓN ---
spark.sql.adaptive.enabled              true
spark.sql.adaptive.coalescePartitions.enabled true
spark.serializer                        org.apache.spark.serializer.KryoSerializer

# --- LOGS ---
spark.ui.showConsoleProgress            true


# --- JAVA 17 ---
# Permisos para Java 17 en el Driver
spark.driver.extraJavaOptions   --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED
# Permisos para Java 17 en los Executors (Workers)
spark.executor.extraJavaOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED