# --- RED ---
spark.driver.bindAddress                0.0.0.0
spark.executor.hostname                 0.0.0.0
spark.network.timeout                   120s
spark.rpc.lookupTimeout                 120s

# --- RECURSOS ---
# Estrategia: Ejecutores potentes. 
# 3GB por core aprovecha los 26GB de RAM sin ahogar el CPU.
spark.executor.memory                   3g
# El driver corre en el Nodo 1 (Manager) que tiene mucha RAM libre. Le damos 4GB.
spark.driver.memory                     4g
spark.executor.cores                    1

# --- DYNAMIC ALLOCATION ---
spark.dynamicAllocation.enabled         true
spark.dynamicAllocation.minExecutors    0
# Permitimos hasta 20 ejecutores para usar todo el cluster si es necesario
spark.dynamicAllocation.maxExecutors    20

spark.dynamicAllocation.executorIdleTimeout        60s
spark.dynamicAllocation.cachedExecutorIdleTimeout  300s

# --- OPTIMIZACIÓN ---
spark.sql.adaptive.enabled              true
spark.serializer                        org.apache.spark.serializer.KryoSerializer
spark.ui.showConsoleProgress            true

# --- PARALELISMO ---
# 14 Cores totales * 3 = 42 particiones.
spark.default.parallelism               42
spark.sql.shuffle.partitions            42