# --- RED ---
spark.driver.bindAddress                0.0.0.0
spark.executor.hostname                 0.0.0.0

# --- RECURSOS ---
# 4GB por executor. 20GB / 4GB = 5 ejecutores en paralelo.
spark.executor.memory                   4g
spark.driver.memory                     2g
spark.executor.cores                    1

# --- DYNAMIC ALLOCATION ---
spark.dynamicAllocation.enabled         true
spark.dynamicAllocation.minExecutors    0
spark.dynamicAllocation.maxExecutors    5

# --- PARALELISMO ---
# 6 Cores * 3 = 18 particiones. 
spark.default.parallelism               18
spark.sql.shuffle.partitions            18

# --- OPTIMIZACIÓN ---
spark.sql.adaptive.enabled              true
spark.serializer                        org.apache.spark.serializer.KryoSerializer