# --- RED ---
spark.driver.bindAddress                0.0.0.0
spark.executor.hostname                 0.0.0.0
spark.network.timeout                   120s
spark.rpc.lookupTimeout                 120s

# --- RECURSOS ---
# 1.5GB por executor permite meter 3 executors en un nodo de 6GB (con espacio sobrado)
spark.executor.memory                   1536m
spark.driver.memory                     1g
spark.executor.cores                    1

# --- DYNAMIC ALLOCATION ---
spark.dynamicAllocation.enabled         true
spark.dynamicAllocation.minExecutors    0
# Tope de 5 contenedores por alumno. Garantiza que todos puedan trabajar.
spark.dynamicAllocation.maxExecutors    5

spark.dynamicAllocation.executorIdleTimeout        60s
spark.dynamicAllocation.cachedExecutorIdleTimeout  300s

# --- OPTIMIZACIÓN ---
spark.sql.adaptive.enabled              true
spark.serializer                        org.apache.spark.serializer.KryoSerializer
spark.ui.showConsoleProgress            true